---
- name: Copy crictl config file to the node
  template:
    src: ../templates/crictl.yaml.j2
    dest: "/etc/crictl.yaml"
    owner: root
    mode: 0644

- name: Copy crictl binary from download dir
  synchronize:
    src: "{{ local_release_dir }}/crictl"
    dest: "{{ bin_dir }}/crictl"
    compress: no
    perms: yes
    owner: no
    group: no
