- name: Download and unarchive containerd
  unarchive:
    src: "{{ containerd_download_url }}"
    dest: /usr/local
    remote_src: yes

- name: Download and unarchive crictl
  unarchive:
    src: "{{ crictl_download_url }}"
    dest: /usr/local/bin
    remote_src: yes

- name: Install crictl config
  template:
    src: crictl.yaml.j2
    dest: /etc/crictl.yaml
    owner: bin
    mode: 0644

- name: Install crictl completion
  shell: /usr/local/bin/crictl completion >/etc/bash_completion.d/crictl
  ignore_errors: True

- name: Download containerd.service
  get_url:
    url: "{{ containerd_service_src }}"
    dest: "{{ containerd_service_dir }}"

- name: Enable containerd
  systemd:
    name: containerd.service
    state: started
    enabled: yes
    daemon-reload: yes

- name: Install runc
  get_url:
    url: "{{ runc_download_url }}"
    dest: /usr/local/bin/runc
    mode: 0755
