---
containerd_version: '1.2.4'
containerd_package: 'containerd.io'

containerd_package_info:
  pkgs:

containerd_repo_key_info:
  repo_keys:

containerd_repo_info:
  repos:

containerd_config:
  systemd_cgroup: false
  grpc:
    max_recv_message_size: 16777216
    max_send_message_size: 16777216
  debug:
    level: ""
  registries:
    "docker.io": "https://registry-1.docker.io"

# Ubuntu docker-ce repo
containerd_ubuntu_repo_base_url: "https://download.docker.com/linux/ubuntu"
containerd_ubuntu_repo_gpgkey: 'https://download.docker.com/linux/ubuntu/gpg'
containerd_ubuntu_repo_repokey: '9DC858229FC7DD38854AE2D88D81803C0EBFCD88'
