---
ingress_nginx_default_backend_image_repo: gcr.io/google_containers/defaultbackend
ingress_nginx_default_backend_image_tag: 1.4

ingress_nginx_controller_image_repo: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
ingress_nginx_controller_image_tag: 0.11.0

ingress_nginx_namespace: "ingress-nginx"
ingress_nginx_insecure_port: 80
ingress_nginx_secure_port: 443
ingress_nginx_configmap: {}
ingress_nginx_configmap_tcp_services: {}
ingress_nginx_configmap_udp_services: {}
